### ISSUE TITLE
Pb de backup fichiers text

### ISSUE THREAD

**Issue by lesurp** [ayMasse/isen_unix_project#1]
Lorsque l'on utulise backup.sh :
Si le fichier est un fichier type texte qui n'a pas été modifié entre deux backups, il est enregistré sous son nom habituel

Ce qui break le restore_backup.sh et le inc_backup (qui doivent de toute façon être améliorés mais bon)

**Comment by aymasse** [comment]
Je n'arrive pas à reproduire ce bug. Si je comprends bien, si tu fais deux backups à la suite (à partir de rien, donc pas d'archive init) le fichier présent dans la deuxième archive est le fichier lui-même et non le patch. De mon côté, en faisant cette manipulation, j'obtiens bien un patch vide dans la deuxième archive.

**Comment by lesurp** [comment]
1. supprime ton .backup
2. crée deux fichiers, un **toUpdate** l'autre **toUpdate.filter**
3. lance backup.sh
4. ??
5. profit pas

en faisant ça j'ai un fichier **toUpdate.patch** qui se créé dans mon dossier courant

et l'archive se fait mal

même pb avec un fichier **_toUpdate.filter** ou **_toUpdate_.filter**

**Comment by aymasse** [comment]
Fichier vide considéré comme binaire
