### ISSUE TITLE
files with similar names

### ISSUE THREAD

**Issue by lesurp** [ayMasse/isen_unix_project#2]
backup.sh marchait pas avec deux fichiers ayant (presque) le même nom
toUpdate
et
toUpdate.filter marchait pas

**Comment by aymasse** [comment]
Je n'arrive pas non plus à repduire (ou comprendre ?) le problème ici.

**Comment by lesurp** [comment]
1. supprime ton .backup
2. crée deux fichiers, un toUpdate l'autre toUpdate.filter
3. lance backup.sh
4. ??
5. profit pas

en faisant ça j'ai un fichier toUpdate.patch qui se créé dans mon dossier courant

et l'archive se fait mal

même pb avec un fichier _toUpdate.filter ou toUpdate.filter
